# Generated by Django 2.0.4 on 2018-04-06 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignacionActivo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('red_bono', models.IntegerField()),
                ('red_efectivo', models.IntegerField()),
                ('red_convertible', models.IntegerField()),
                ('red_acciones', models.IntegerField()),
                ('red_preferida', models.IntegerField()),
                ('red_otra', models.IntegerField()),
                ('portafolio_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='categoriaGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categoriaMoneda',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('categoriaGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.categoriaGrupo')),
            ],
        ),
        migrations.CreateModel(
            name='domicilio',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estadoDistribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fondo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estadoDistribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.estadoDistribucion')),
            ],
        ),
        migrations.CreateModel(
            name='frecuenciaDistribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_legal', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('categoriaMoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.categoriaMoneda')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='moneda',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='morningstar',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country_exposure', models.TextField()),
                ('asignacionActivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.asignacionActivo')),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rendimiento',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rentaFija',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('bsed', models.IntegerField()),
                ('bsem', models.IntegerField()),
                ('bsmd', models.IntegerField()),
                ('bsym', models.IntegerField()),
                ('cred', models.IntegerField()),
                ('crem', models.IntegerField()),
                ('crmd', models.IntegerField()),
                ('crym', models.IntegerField()),
                ('portafolio_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('materiales_basicos', models.IntegerField()),
                ('servicio_comunicacion', models.IntegerField()),
                ('ciclico_consumidor', models.IntegerField()),
                ('defensa_consumidor', models.IntegerField()),
                ('energia', models.IntegerField()),
                ('servicios_financieros', models.IntegerField()),
                ('cuidado_salud', models.IntegerField()),
                ('acciones_industriales', models.IntegerField()),
                ('portafolio_fecha', models.DateField()),
                ('bienes_raices', models.IntegerField()),
                ('tecnologia', models.IntegerField()),
                ('utilidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoFondo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='morningstar',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.sector'),
        ),
        migrations.AddField(
            model_name='fund',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.moneda'),
        ),
        migrations.AddField(
            model_name='fund',
            name='tipoFondo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoFondo'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='frecuenciaDistribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.frecuenciaDistribucion'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.fund'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.marca'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='morningstar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.morningstar'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.proveedor'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='rendimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.rendimiento'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='rentaFija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.rentaFija'),
        ),
    ]
