# Generated by Django 2.0.4 on 2018-04-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_exposure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='branding',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='broadCategory',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='carteraCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('broadCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.broadCategory')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='domicilio',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fondo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_legal', models.CharField(max_length=50)),
                ('fecha_inicio', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.categoria')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='frecuenciaDistribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='moneda',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('numero_cuotas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('datos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rendimiento',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='saldoInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField()),
                ('fecha', models.CharField(max_length=50)),
                ('numero_cuotas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoInstrumento',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('estructura_legal', models.CharField(max_length=50)),
                ('estado_distribucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoInversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='asignacionActivo',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('red_bono', models.FloatField()),
                ('red_efectivo', models.FloatField()),
                ('red_convertible', models.FloatField()),
                ('red_preferida', models.FloatField()),
                ('red_acciones', models.FloatField()),
                ('red_otra', models.FloatField()),
                ('portafolio_fecha', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='claseActivo',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('datos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='instrumento',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('run_svs', models.CharField(max_length=50)),
                ('clase_proveedor', models.CharField(max_length=50)),
                ('operation_ready', models.IntegerField()),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.branding')),
            ],
        ),
        migrations.CreateModel(
            name='rentaFija',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('bsed', models.FloatField()),
                ('bsem', models.FloatField()),
                ('bsmd', models.FloatField()),
                ('bsym', models.FloatField()),
                ('cred', models.FloatField()),
                ('crem', models.FloatField()),
                ('crmd', models.FloatField()),
                ('crym', models.FloatField()),
                ('portafolio_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('materiales_basicos', models.FloatField()),
                ('servicio_comunicacion', models.FloatField()),
                ('ciclico_consumidor', models.FloatField()),
                ('defensa_consumidor', models.FloatField()),
                ('energia', models.FloatField()),
                ('servicios_financieros', models.FloatField()),
                ('cuidado_salud', models.FloatField()),
                ('acciones_industriales', models.FloatField()),
                ('bienes_raices', models.FloatField()),
                ('tecnologia', models.FloatField()),
                ('utilidades', models.FloatField()),
                ('portafolio_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='valorCuota',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('anio', models.CharField(max_length=50)),
                ('datos', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='saldoinicial',
            name='bindex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.bindex'),
        ),
        migrations.AddField(
            model_name='saldoinicial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.cliente'),
        ),
        migrations.AddField(
            model_name='saldoinicial',
            name='tipoInversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoInversion'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='bindex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.bindex'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.cliente'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipoInversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoInversion'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipoMovimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoMovimiento'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.moneda'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='tipoInstrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoInstrumento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoInversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoInversion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.moneda'),
        ),
        migrations.AddField(
            model_name='carteracliente',
            name='bindex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.bindex'),
        ),
        migrations.AddField(
            model_name='carteracliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.cliente'),
        ),
        migrations.AddField(
            model_name='carteracliente',
            name='tipoInversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoInversion'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='fondo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.fondo'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='frecuenciaDistribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.frecuenciaDistribucion'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.proveedor'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='rendimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.rendimiento'),
        ),
    ]
