# Generated by Django 2.0.4 on 2018-05-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipoInversion',
        ),
    ]
