# Generated by Django 2.0.4 on 2018-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldomensual',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='mes',
            field=models.IntegerField(),
        ),
    ]
