# Generated by Django 2.0.4 on 2018-05-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0002_remove_cliente_tipoinversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoinstrumento',
            old_name='ffmm_internacional',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='tipoinstrumento',
            name='ffmm_nacional',
        ),
    ]
