# Generated by Django 2.0.4 on 2018-05-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0002_auto_20180503_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipoMovimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoMovimiento'),
        ),
    ]
