# Generated by Django 2.0.4 on 2018-05-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0003_remove_proveedor_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryExposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.TextField()),
                ('bindex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuario.bindex')),
            ],
        ),
    ]
