# Generated by Django 2.0.4 on 2018-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0004_countryexposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
