# Generated by Django 2.0.4 on 2018-05-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0005_instrumento_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='precio_actual',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('DayEndNAVDate', models.DateField(blank=True, null=True)),
                ('DayEndNAV', models.FloatField(blank=True, null=True)),
                ('MonthEndNAVDate', models.DateField(blank=True, null=True)),
                ('MonthEndNAV', models.FloatField(blank=True, null=True)),
                ('UnsplitNAV', models.FloatField(blank=True, null=True)),
                ('NAV52wkHigh', models.FloatField(blank=True, null=True)),
                ('NAV52wkHighDate', models.DateField(blank=True, null=True)),
                ('NAV52wkLow', models.FloatField(blank=True, null=True)),
                ('NAV52wkLowDate', models.DateField(blank=True, null=True)),
                ('PerformanceReturnSource', models.CharField(blank=True, max_length=20, null=True)),
                ('CurrencyISO3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='rentabilidad',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('DayEndDate', models.DateField(blank=True, null=True)),
                ('DayEndNAV', models.FloatField(blank=True, null=True)),
                ('NAVChange', models.FloatField(blank=True, null=True)),
                ('NAVChangePercentage', models.FloatField(blank=True, null=True)),
                ('Retorno', models.TextField(blank=True, null=True)),
                ('Rank', models.TextField(blank=True, null=True)),
                ('CategoryEndDate', models.DateField(blank=True, null=True)),
                ('CategoryReturn', models.TextField(blank=True, null=True)),
                ('CategorySize', models.TextField(blank=True, null=True)),
                ('PricingFrequency', models.CharField(blank=True, max_length=20, null=True)),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.fondo')),
            ],
        ),
        migrations.CreateModel(
            name='reporte_anual_couta',
            fields=[
                ('bindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex')),
                ('AnnualReportDate', models.DateField(blank=True, null=True)),
                ('NetExpenseRatio', models.FloatField(blank=True, null=True)),
                ('AnnualReportPerformanceFee', models.FloatField(blank=True, null=True)),
                ('InterimNetExpenseRatioDate', models.DateField(blank=True, null=True)),
                ('InterimNetExpenseRatio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='countryexposure',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='countryexposure',
            name='id',
        ),
        migrations.AddField(
            model_name='countryexposure',
            name='country_exposure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countryexposure',
            name='country_exposure_bond',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countryexposure',
            name='country_exposure_convertible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countryexposure',
            name='country_exposure_equity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryexposure',
            name='bindex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuario.bindex'),
        ),
    ]
