# Generated by Django 2.0.5 on 2018-05-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0007_pais_nombre_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.branding'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='clase_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.fondo'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='frecuenciaDistribucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.frecuenciaDistribucion'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='operation_ready',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.proveedor'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='rendimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.rendimiento'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='run_svs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='tipoInstrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.tipoInstrumento'),
        ),
    ]
