# Generated by Django 2.0.5 on 2018-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0009_auto_20180529_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionactivo',
            name='portafolio_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='red_acciones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='red_bono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='red_convertible',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='red_efectivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='red_otra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='red_preferida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='acciones_industriales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='bienes_raices',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='ciclico_consumidor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='cuidado_salud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='defensa_consumidor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='energia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='materiales_basicos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='portafolio_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='servicio_comunicacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='servicios_financieros',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='tecnologia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='utilidades',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
