# Generated by Django 2.0.5 on 2018-05-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0010_auto_20180529_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuario.categoria'),
        ),
        migrations.AlterField(
            model_name='fondo',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fondo',
            name='nombre_legal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
