# Generated by Django 2.0.5 on 2018-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0011_auto_20180530_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Amaterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Apaterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
