# Generated by Django 2.0.6 on 2018-06-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0013_auto_20180604_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reporte_anual_couta',
            new_name='reporte_anual_cuota',
        ),
    ]
